package lk.ijse.spiceExportCompany.util;

public enum Routes {
    MAIN,LOGIN,MANAGERDASHBOARD,EMPLOYEEMANAGEMENT,FARMERMANAGEMENT,FARMERS,TYPESOFGOODSSUPPLIEDBYFARMER,FARMERSPAMENTS,STOCK,TRANSPORTMANAGEMENT,VEHICLE,DRIVER,CUSTOMERS,ORDER,PRODUCT,PLACEORDERMANAGEMENT

}
